obj-$(CONFIG_PMC_ATOM)		+= pmc_atom.o
obj-$(CONFIG_PUNIT_ATOM_DEBUG)	+= punit_atom_debug.o

# BOARD files
+obj-y	+= platform_mt9m114.o
+obj-y 	+= platform_ov5640_2.o
+obj-y 	+= platform_ov5640_1.o
+obj-y	+= platform_camera.o
+obj-y	+= byt_plat_clock.o
